project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('save.urls', namespace='core'))
]

save/urls.py
from django.urls import path, register_converter
from save import views

# register_converter(views.PersonDetailConverter, 'num')

app_name = 'save'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('persons/', views.PersonsView.as_view(), name='persons'),
    path('person/<int:pk>', views.PersonDetailView.as_view(), name='person'),
    path('person/', views.person_detail_get, name='person_detail_get'),
    path('person/add/', views.add_person, name='add_person'),
    path('appeals/', views.AppealsView.as_view(), name='appeals'),
    path('appeal/<int:pk>', views.appeal, name='appeal'),
    path('appeal/add/', views.add_appeal, name='add_appeal'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('service/<int:pk>', views.service, name='service'),
    path('service/add/', views.add_service, name='add_service'),
]

save/models.py
import uuid
from django.db import models


class Service(models.Model):
    """"Класс службы."""
    name = models.CharField('Название службы', max_length=255)
    code = models.CharField('Код службы', max_length=255)
    number = models.PositiveIntegerField('Номер телефона службы')

    class Meta:
        verbose_name = 'Служба'
        verbose_name_plural = 'Службы'
        ordering = ('-code',)

    def __str__(self):
        return self.name


class Person(models.Model):
    """Класс заявителя."""
    last_name = models.CharField('Фамилия', max_length=255)
    first_name = models.CharField('Имя', max_length=255)
    patronymic = models.CharField('Отчество', max_length=255)
    birthdate = models.DateField('Дата рождения')
    phone_number = models.PositiveIntegerField('Номер телефона', blank=True, null=True)
    health_condition = models.TextField(
        'Состояния здоровья',
        blank=True,
        default='практически здоров',
        help_text='аллергоанамнез, хронические заболевание и т.п.'
    )
    GENDER = [
        ('М', 'Мужской'),
        ('Ж', 'Женский'),
    ]
    gender = models.CharField('Пол', max_length=255, choices=GENDER, blank=True)
    photo = models.ImageField('Изображение', blank=True)

    class Meta:
        verbose_name = 'Заявитель'
        verbose_name_plural = 'Заявители'
        ordering = ('last_name', 'first_name', 'patronymic')

    def full_name(self):
        return f'{self.last_name} {self.first_name} {self.patronymic}'

    def __str__(self):
        return self.full_name()


class Appeal(models.Model):
    """Класс обращения."""
    date = models.DateTimeField('Дата', auto_now_add=True)
    number = models.UUIDField(
        'Номер карточки',
        default=uuid.uuid4,
        editable=False,
        unique=True
    )  # что за индексирование, db_index
    person = models.ForeignKey(
        Person,
        verbose_name='Заявитель',
        related_name='appeals',
        on_delete=models.CASCADE
    )
    PRO = 'worked'
    END = 'finish'
    STATUS_CHOICES = [
        (PRO, 'В работе'),
        (END, 'Завершено'),
    ]
    status = models.CharField('Статус', max_length=255, default=PRO, choices=STATUS_CHOICES)
    number_of_victims = models.PositiveIntegerField('Количество пострадавших')
    not_call = models.BooleanField('Не звонить')
    service = models.ManyToManyField(Service, related_name='appeals')

    class Meta:
        verbose_name = 'Обращение'
        verbose_name_plural = 'Обращения'
        ordering = ('date', 'number')

    def __str__(self):
        return f'{self.number}'

save/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *
import datetime


class AddAppealForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        widgets = {
            'service': forms.CheckboxInput(),
        }

    class Meta:
        model = Appeal
        fields = ('person', 'status', 'number_of_victims', 'not_call', 'service')


class AddPersonForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        widgets = {
            'health_condition': forms.Textarea(attrs={'cols': 50, 'rows': 20}),
        }

    class Meta:
        model = Person
        fields = ('last_name', 'first_name', 'patronymic', 'birthdate', 'gender', 'phone_number', 'health_condition')

    def clean_birthdate(self):
        birthdate = self.cleaned_data['birthdate']
        if birthdate > datetime.datetime.today().date():
            raise ValidationError('Введите правильную дату рождения')

        return birthdate

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if len(str(phone_number)) > 11:
            raise ValidationError('Длина номера телефона должна быть 11')


class AddServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'code', 'number')
        help_texts = {
            'code': 'Пример: 101, 102, 103',
        }

save/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, ListView, DetailView

from save.models import *
from save.forms import *
from django.db.models import Avg, Count


class IndexView(TemplateView):
    template_name = 'save/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        context['count'] = Appeal.objects.count()
        return context


class PersonDetailView(DetailView):
    model = Person
    template_name = 'save/person.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Информация о заявителе'
        return context


def person_detail_get(request):
    number = request.GET.get('number')
    qs = Person.objects.filter(phone_number=number)
    return JsonResponse(qs.values().first())


# class PersonDetailConverter:
#     regex = '[0-9]{11}'
#
#     def to_python(self, value):
#         return int(value)


class PersonsView(TemplateView):
    template_name = 'save/persons.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['persons'] = Person.objects.all()
        return context


def add_person(request):
    if request.method == 'POST':
        form = AddPersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('persons')
    else:
        form = AddPersonForm()
    return render(request, 'save/add_person.html', {'form': form, 'title': 'Добавление заявителя'})


class AppealsView(ListView):
    model = Appeal
    template_name = 'save/appeals.html'
    context_object_name = 'appeals'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['average_amount'] = Appeal.objects.annotate(Count('service')).aggregate(Avg('service__count'))['service__count__avg']
        return context


def add_appeal(request):
    if request.method == 'POST':
        form = AddAppealForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('appeals')
    else:
        form = AddAppealForm()
    return render(request, 'save/add_appeal.html', {'form': form, 'title': 'Добавить обращение'})


def appeal(request, pk):
    qs = Appeal.objects.filter(id=pk)
    return JsonResponse(qs.values().first())


class ServicesView(TemplateView):
    template_name = 'save/services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        return context


def service(request, pk):
    qs = Service.objects.filter(id=pk)
    return JsonResponse(qs.values().first())


def add_service(request):
    if request.method == 'POST':
        form = AddServiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('services')
    else:
        form = AddServiceForm()
    return render(request, 'save/add_service.html', {'form': form, 'title': 'Добавление службы'})

save/templates/save/add_appeal.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

<form action="{% url 'core:add_appeal' %}" method="post">
    <p><a href="{% url 'core:add_person' %}">Создать нового заявителя</a></p>
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Добавить</button>
</form>

{% endblock %}

save/templates/save/add_person.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

<form action="{% url 'core:add_person' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>

{% endblock %}

save/templates/save/add_service.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

<form action="{% url 'core:add_service' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>

{% endblock %}

save/templates/save/appeal.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ number }}</h1>
{% endblock %}

save/templates/save/appeals.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}
{%block content %}
    <h2 style="display: inline-block">Обращения</h2>
    <p style="display: inline; margin-left: 3%"><a href="{% url 'core:add_appeal' %}">Создать новое обращение</a></p>
    <h2>Среднее количество вызванных служб: {{ average_amount }}</h2>
    <br>
    {% for appeal in appeals %}
        <h3><a href="{% url 'core:appeal' appeal.id %}">{{ appeal }}</a><span>   {{appeal.date|date:'j.m.o H:i:s '}} {{ appeal.date|timesince }} </span></h3>
        <span>Звонить: {{ appeal.status|yesno }}</span><br>

        <span style="font-size: 11px">
            {{ appeal.service.all|join:', '|upper }}
            {% for i in appeal.service.all %}
            {% empty %}
                <span style="font-size: 13px">Службы не назначены</span>
            {% endfor %}</span>
<hr>
    {% endfor %}
    <footer>
        <h3>Общее число обращений: {{ appeals|length }}</h3>
        {% include 'save/footer.html'%}
    </footer>
{% endblock %}

save/templates/save/footer.html
<h3>15.12.2022</h3>

save/templates/save/index.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ count }}</h1>
    <h3><a href="{% url 'core:appeals' %}">Обращения</a></h3>
    <h3><a href="{% url 'core:persons' %}">Заявители</a></h3>
    <h3><a href="{% url 'core:services' %}">Службы</a></h3>
{% endblock %}

save/templates/save/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

save/templates/save/person.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>{{ title }}</h2>
    <h3>Заявитель: {{ person.full_name|lower|title }}</h3>
    <h3>Дата рождения: {{ person.birthdate|date }}</h3>
    <h3>Пол: {{ person.gender }}</h3>
    <h3>Номер телефона: {{ person.phone_number|default_if_none:'не указан' }}</h3>
    <h3>Состояние здоровья: {{ person.health_condition }}</h3>
    <h3>Фотография: {{ person.photo|default:'-' }}</h3>
{% endblock %}

save/templates/save/persons.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}
{%block content %}
    <h2 style="display: inline-block">Заявители</h2>
    <p style="display: inline; margin-left: 3%"><a href="{% url 'core:add_person' %}">Создать нового заявителя</a></p>
    {% for person in persons %}
        {% if forloop.first %}
            <h3><span>{{ forloop.counter }}    </span><a href="{% url 'core:person' person.id %}" style="color: orangered">{{ person }}</a></h3>
        {% elif forloop.last %}
            <h3><span>{{ forloop.counter }}    </span><a href="{% url 'core:person' person.id %}" style="color: orangered">{{ person }}</a></h3>
        {% else %}
            <h3><span>{{ forloop.counter }}    </span><a href="{% url 'core:person' person.id %}">{{ person }}</a></h3>
        {% endif %}
    {% endfor %}
    <footer>{% include 'save/footer.html'%}</footer>
{% endblock %}

save/templates/save/services.html
{% extends 'save/layout.html' %}

{% block title %}{{ title }}{% endblock %}
{%block content %}
    <h2 style="display: inline-block">Службы</h2>
    <p style="display: inline; margin-left: 3%"><a href="{% url 'core:add_service' %}">Создать новую службу</a></p>
    {% for service in services %}
        <h3><a href="{% url 'core:service' service.id %}">{{ service }}</a></h3>
    {% endfor %}
    <footer>{% include 'save/footer.html'%}</footer>
{% endblock %}